apiVersion: apps/v1
kind: Deployment
metadata:
  name: broc-schema-registry
  namespace: broc-kafka
  labels:
    app: broc-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broc-schema-registry
  template:
    metadata:
      labels:
        app: broc-schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:5.5.0
          env:
          - name: SCHEMA_REGISTRY_HOST_NAME
            value: broc-schema-registry
          - name: SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL
            value: "NONE"
          - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
            value: PLAINTEXT://ib-kafka-headless.ib-kafka:9093
          ports:
          - containerPort: 8081
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: broc-schema-registry
  namespace: broc-kafka
  labels:
    app: broc-schema-registry
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: broc-schema-registry