apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jsonschemas.tagging-v2.infoblox.com
spec:
  group: tagging-v2.infoblox.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                registry:
                  type: string
                schema:
                  type: string
                name:
                  type: string
  scope: Namespaced
  names:
    plural: jsonschemas
    singular: jsonschema
    kind: JsonSchema
    shortNames:
      - js
