{{- if .Values.schemaregistry.enabled }}
apiVersion: "schemaregistry.infoblox.com/v1"
kind: Jsonschema
metadata:
  name: atlas.tagging-pb-namespace
spec:
  name: atlas.tagging-pb-Namespace
  schema: |
    {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "x-csv-common-name": "TestCommon",
            "x-csv-full-name": "test.full.name",
            "properties": {
                "id": {
                    "properties": {
                        "application_name": {
                            "type": "string",
                            "description": "An application identifier that will be used among\n other infrastructure services to identify the application"
                        },
                        "resource_type": {
                            "type": "string",
                            "description": "An application specific type name of a resource"
                        },
                        "resource_id": {
                            "type": "string",
                            "description": "An application specific resource identity of a resource"
                        }
                    },
                    "additionalProperties": true,
                    "type": "object"
                },
                "name": {
                    "type": "string",
                    "description": "Human-readable name for namespace."
                },
                "created_at": {
                    "type": "string",
                    "description": "Read-only. Timestamp created_at, equals to time when particular object was created.",
                    "format": "date-time"
                },
                "updated_at": {
                    "type": "string",
                    "description": "Read-only. Timestamp updated_at, equals to time when particular object was updated, by default equals to created_at.",
                    "format": "date-time"
                },
                "deleted_at": {
                    "type": "string",
                    "description": "Read-only. Timestamp deleted_at, equals to time when particular object was deleted, by default equals to null.",
                    "format": "date-time"
                },
                "type": {
                    "type": "string",
                    "description": "The namespace type. It is one of [\"freeform\",  \"locked\", \"system\"]. By default equals to \"freeform\"."
                }
            },
            "additionalProperties": true,
            "type": "object"
        }
---
apiVersion: "schemaregistry.infoblox.com/v1"
kind: Jsonschema
metadata:
  name: atlas.tagging-pb-tag
spec:
  name: atlas.tagging-pb-Tag
  schema: |
    {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "x-csv-common-name": "TestCommon",
            "x-csv-full-name": "test.full.name",
            "properties": {
                "id": {
                    "$ref": "atlas.rpc.Identifier",
                    "additionalProperties": true,
                    "type": "object"
                },
                "key": {
                    "type": "string",
                    "description": "The tag key."
                },
                "type": {
                    "type": "string",
                    "description": "The tag type. It is one of [\"freeform\",  \"restricted\"]. By default equals to \"freeform\"."
                },
                "regexp": {
                    "type": "string",
                    "description": "The tag regexp. POSIX regexp string, used for values validation. By default equals to \"*\"(allow all)."
                },
                "values": {
                    "items": {
                        "$schema": "http://json-schema.org/draft-04/schema#",
                        "properties": {
                            "id": {
                                "$ref": "atlas.rpc.Identifier",
                                "additionalProperties": true,
                                "type": "object"
                            },
                            "value": {
                                "type": "string",
                                "description": "The value."
                            },
                            "created_at": {
                                "type": "string",
                                "description": "Read-only. Timestamp created_at, equals to time when particular object was created.",
                                "format": "date-time"
                            },
                            "deleted_at": {
                                "type": "string",
                                "description": "Read-only. Timestamp deleted_at, equals to time when particular object was deleted, by default equals to null.",
                                "format": "date-time"
                            }
                        },
                        "additionalProperties": true,
                        "type": "object"
                    },
                    "type": "array",
                    "description": "The values is a repeated value objects which belongs to particular tag."
                },
                "created_at": {
                    "type": "string",
                    "description": "Read-only. Timestamp created_at, equals to time when particular object was created.",
                    "format": "date-time"
                },
                "updated_at": {
                    "type": "string",
                    "description": "Read-only. Timestamp updated_at, equals to time when particular object was updated, by default equals to created_at.",
                    "format": "date-time"
                },
                "deleted_at": {
                    "type": "string",
                    "description": "Read-only. Timestamp deleted_at, equals to time when particular object was deleted, by default equals to null.",
                    "format": "date-time"
                },
                "regexp_description": {
                    "type": "string",
                    "description": "The regexp_description, optional description for regexp field."
                },
                "status": {
                    "type": "string",
                    "description": "The tag status. It is one of [\"active\",  \"revoked\"]. By default equals to \"active\"."
                },
                "namespace": {
                    "properties": {
                        "id": {
                            "$ref": "atlas.rpc.Identifier",
                            "additionalProperties": true,
                            "type": "object"
                        },
                        "name": {
                            "type": "string",
                            "description": "Human-readable name for namespace."
                        },
                        "created_at": {
                            "type": "string",
                            "description": "Read-only. Timestamp created_at, equals to time when particular object was created.",
                            "format": "date-time"
                        },
                        "updated_at": {
                            "type": "string",
                            "description": "Read-only. Timestamp updated_at, equals to time when particular object was updated, by default equals to created_at.",
                            "format": "date-time"
                        },
                        "deleted_at": {
                            "type": "string",
                            "description": "Read-only. Timestamp deleted_at, equals to time when particular object was deleted, by default equals to null.",
                            "format": "date-time"
                        },
                        "type": {
                            "type": "string",
                            "description": "The namespace type. It is one of [\"freeform\",  \"locked\", \"system\"]. By default equals to \"freeform\"."
                        }
                    },
                    "additionalProperties": true,
                    "type": "object",
                    "description": "The namespace is a reference of an namespace object to which tag belongs."
                },
                "version": {
                    "type": "integer",
                    "description": "The version is used to prevent multiple users from updating the same tag simultaneously"
                }
            },
            "additionalProperties": true,
            "type": "object",
            "definitions": {
                "atlas.rpc.Identifier": {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "properties": {
                        "application_name": {
                            "type": "string",
                            "description": "An application identifier that will be used among\n other infrastructure services to identify the application"
                        },
                        "resource_type": {
                            "type": "string",
                            "description": "An application specific type name of a resource"
                        },
                        "resource_id": {
                            "type": "string",
                            "description": "An application specific resource identity of a resource"
                        }
                    },
                    "additionalProperties": true,
                    "type": "object",
                    "description": "A number of application services require a mechanism to\n encode the identity of a particular resource across applications.\n The resource identifiers consist of the application ID,\n an application-defined resource type,\n and an application-defined ID for that resource",
                    "id": "atlas.rpc.Identifier"
                }
            }
        }
---
apiVersion: "schemaregistry.infoblox.com/v1"
kind: Jsonschema
metadata:
  name: atlas.tagging-pb-value
spec:
  name: atlas.tagging-pb-Value
  schema: |
    {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "x-csv-common-name": "TestCommon",
            "x-csv-full-name": "test.full.name",
            "properties": {
                "id": {
                    "properties": {
                        "application_name": {
                            "type": "string",
                            "description": "An application identifier that will be used among\n other infrastructure services to identify the application"
                        },
                        "resource_type": {
                            "type": "string",
                            "description": "An application specific type name of a resource"
                        },
                        "resource_id": {
                            "type": "string",
                            "description": "An application specific resource identity of a resource"
                        }
                    },
                    "additionalProperties": true,
                    "type": "object"
                },
                "value": {
                    "type": "string",
                    "description": "The value."
                },
                "created_at": {
                    "type": "string",
                    "description": "Read-only. Timestamp created_at, equals to time when particular object was created.",
                    "format": "date-time"
                },
                "deleted_at": {
                    "type": "string",
                    "description": "Read-only. Timestamp deleted_at, equals to time when particular object was deleted, by default equals to null.",
                    "format": "date-time"
                }
            },
            "additionalProperties": true,
            "type": "object"
        }
{{- end }}
