{{- if .Values.schemaregistry.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jsonschemas.schemaregistry.infoblox.com
spec:
  group: schemaregistry.infoblox.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                schema:
                  type: string
                name:
                  type: string
  scope: Namespaced
  names:
    plural: jsonschemas
    singular: jsonschema
    kind: Jsonschema
    shortNames:
      - js
{{- end }}
